export const DEPARTMENTS = [
  "Recepção",
  "Portaria",
  "DP",
  "RH",
  "PCP",
  "Estoque",
  "T.I",
  "Marketing",
  "Expansão",
  "Comercial Interno",
  "Compras",
  "BRG",
  "Controladoria",
  "Diretoria",
  "Financeiro",
  "Fiscal",
  "Segurança do Trabalho",
  "Grafica",
  "Logistica",
  "Patrimonio",
  "Camara fria",
  "Oficina",
  "Manutenção",
  "Produção",
  "P&D",
  "Qualidade",
  "Monitoramento",
  "Comercial Externo/Vendas",
  "Externos",
  "Outros",
];
